"""initial_tables

Revision ID: 12fb7f608749
Revises: 
Create Date: 2026-05-31 17:06:56.175569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12fb7f608749'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_reels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('source_video_media_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_reels_owner_id'), 'trip_reels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_trip_reels_trip_id'), 'trip_reels', ['trip_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('place_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(title) >= 1', name='ck_trips_title_not_empty'),
    sa.CheckConstraint('end_date >= start_date', name='ck_trips_end_gte_start'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trips_deleted_at', 'trips', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_trips_owner_id'), 'trips', ['owner_id'], unique=False)
    op.create_table('video_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_media_owner_id'), 'video_media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_video_media_trip_id'), 'video_media', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_media_trip_id'), table_name='video_media')
    op.drop_index(op.f('ix_video_media_owner_id'), table_name='video_media')
    op.drop_table('video_media')
    op.drop_index(op.f('ix_trips_owner_id'), table_name='trips')
    op.drop_index('ix_trips_deleted_at', table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_trip_reels_trip_id'), table_name='trip_reels')
    op.drop_index(op.f('ix_trip_reels_owner_id'), table_name='trip_reels')
    op.drop_table('trip_reels')
    op.drop_table('profiles')
    # ### end Alembic commands ###
